# City to Voivodeship mapping dictionary
CITY_TO_VOIVODESHIP = {
    # MAZOWIECKIE (Masovian Voivodeship) - Capital: Warsaw
    'warszawa': 'MAZOWIECKIE',
    'płock': 'MAZOWIECKIE',
    'radom': 'MAZOWIECKIE',
    'siedlce': 'MAZOWIECKIE',
    'ostrołęka': 'MAZOWIECKIE',
    'legionowo': 'MAZOWIECKIE',
    'pruszków': 'MAZOWIECKIE',
    'piaseczno': 'MAZOWIECKIE',
    'marki': 'MAZOWIECKIE',
    'kobyłka': 'MAZOWIECKIE',
    'sulejówek': 'MAZOWIECKIE',
    'wołomin': 'MAZOWIECKIE',
    'grodzisk mazowiecki': 'MAZOWIECKIE',
    'żyrardów': 'MAZOWIECKIE',
    'ciechanów': 'MAZOWIECKIE',
    'ząbki': 'MAZOWIECKIE',
    'józefów': 'MAZOWIECKIE',
    'otwock': 'MAZOWIECKIE',
    'garwolin': 'MAZOWIECKIE',
    'karczew': 'MAZOWIECKIE',
    'mińsk mazowiecki': 'MAZOWIECKIE',
    'węgrów': 'MAZOWIECKIE',
    'sokołów podlaski': 'MAZOWIECKIE',
    'łukow': 'MAZOWIECKIE',
    'grójec': 'MAZOWIECKIE',
    'góra kalwaria': 'MAZOWIECKIE',
    'konstancin-jeziorna': 'MAZOWIECKIE',
    'milanówek': 'MAZOWIECKIE',
    'brwinów': 'MAZOWIECKIE',
    'piastów': 'MAZOWIECKIE',
    'ursus': 'MAZOWIECKIE',
    'błonie': 'MAZOWIECKIE',
    'leszno': 'MAZOWIECKIE',
    'gostynin': 'MAZOWIECKIE',
    'płońsk': 'MAZOWIECKIE',
    'mława': 'MAZOWIECKIE',
    'mszczonów': 'MAZOWIECKIE',
    'maków mazowiecki': 'MAZOWIECKIE',
    'przasnysz': 'MAZOWIECKIE',
    'żuromin': 'MAZOWIECKIE',
    'pułtusk': 'MAZOWIECKIE',
    'serock': 'MAZOWIECKIE',
    'nowy dwór mazowiecki': 'MAZOWIECKIE',
    'sochaczew': 'MAZOWIECKIE',
    'łowicz': 'MAZOWIECKIE',
    'skierniewice': 'MAZOWIECKIE',
    'białobrzegi': 'MAZOWIECKIE',
    'szydłowiec': 'MAZOWIECKIE',
    'kozienice': 'MAZOWIECKIE',
    'zwoleń': 'MAZOWIECKIE',
    'lipsko': 'MAZOWIECKIE',
    'iłża': 'MAZOWIECKIE',
    'dęblin': 'MAZOWIECKIE',
    # Warsaw districts
    'bemowo': 'MAZOWIECKIE',
    'białołęka': 'MAZOWIECKIE',
    'bielany': 'MAZOWIECKIE',
    'mokotów': 'MAZOWIECKIE',
    'ochota': 'MAZOWIECKIE',
    'praga północ': 'MAZOWIECKIE',
    'praga południe': 'MAZOWIECKIE',
    'śródmieście': 'MAZOWIECKIE',
    'targówek': 'MAZOWIECKIE',
    'ursus': 'MAZOWIECKIE',
    'ursynów': 'MAZOWIECKIE',
    'wawer': 'MAZOWIECKIE',
    'wilanów': 'MAZOWIECKIE',
    'włochy': 'MAZOWIECKIE',
    'wola': 'MAZOWIECKIE',
    'żoliborz': 'MAZOWIECKIE',
    'bródno': 'MAZOWIECKIE',
    'grochów': 'MAZOWIECKIE',
    'gocław': 'MAZOWIECKIE',
    'kabaty': 'MAZOWIECKIE',
    'falenica': 'MAZOWIECKIE',
    'miedzeszyn': 'MAZOWIECKIE',
    'marysin wawerski': 'MAZOWIECKIE',
    'anin': 'MAZOWIECKIE',
    'wesola': 'MAZOWIECKIE',
    'wesoła': 'MAZOWIECKIE',
    'białołęka dworska': 'MAZOWIECKIE',
    'chomiczówka': 'MAZOWIECKIE',
    'muranów': 'MAZOWIECKIE',
    'górny mokotów': 'MAZOWIECKIE',
    'dolny mokotów': 'MAZOWIECKIE',
    'mokotów-siekierki': 'MAZOWIECKIE',
    'mokotów/ursynów': 'MAZOWIECKIE',
    'miasteczko wilanów': 'MAZOWIECKIE',
    'blizne jasińskiego': 'MAZOWIECKIE',
    'bemowo/ blizne jasińskiego': 'MAZOWIECKIE',
    'bielany/bemowo': 'MAZOWIECKIE',
    'marysin': 'MAZOWIECKIE',
    'marysin doły': 'MAZOWIECKIE',
    'marysin wawer': 'MAZOWIECKIE',
    'marysin-doły': 'MAZOWIECKIE',
    'gocławek': 'MAZOWIECKIE',
    'bialoleka': 'MAZOWIECKIE',
    'białobłęka': 'MAZOWIECKIE',
    'białoleka': 'MAZOWIECKIE',
    'białolęka': 'MAZOWIECKIE',
    'białołęka': 'MAZOWIECKIE',
    'bieńkowice': 'MAZOWIECKIE',
    'azory': 'MAZOWIECKIE',
    'arturówek': 'MAZOWIECKIE',
    'anina': 'MAZOWIECKIE',
    'jabłonna': 'MAZOWIECKIE',
    'józefosław': 'MAZOWIECKIE',
    'józefowiec': 'MAZOWIECKIE',
    'julianów': 'MAZOWIECKIE',
    'justynów': 'MAZOWIECKIE',
    'kajetany': 'MAZOWIECKIE',
    'miłosna': 'MAZOWIECKIE',
    'morena': 'MAZOWIECKIE',
    'mrowiny': 'MAZOWIECKIE',
    'mrozów': 'MAZOWIECKIE',

    # MAŁOPOLSKIE (Lesser Poland Voivodeship) - Capital: Krakow
    'kraków': 'MAŁOPOLSKIE',
    'krakow': 'MAŁOPOLSKIE',
    'tarnów': 'MAŁOPOLSKIE',
    'nowy sącz': 'MAŁOPOLSKIE',
    'oświęcim': 'MAŁOPOLSKIE',
    'wieliczka': 'MAŁOPOLSKIE',
    'zakopane': 'MAŁOPOLSKIE',
    'chrzanów': 'MAŁOPOLSKIE',
    'olkusz': 'MAŁOPOLSKIE',
    'skawina': 'MAŁOPOLSKIE',
    'andrychów': 'MAŁOPOLSKIE',
    'bochnia': 'MAŁOPOLSKIE',
    'trzebinia': 'MAŁOPOLSKIE',
    'wadowice': 'MAŁOPOLSKIE',
    'myślenice': 'MAŁOPOLSKIE',
    'proszowice': 'MAŁOPOLSKIE',
    'krzeszowice': 'MAŁOPOLSKIE',
    'słomniki': 'MAŁOPOLSKIE',
    'miechów': 'MAŁOPOLSKIE',
    'gorlice': 'MAŁOPOLSKIE',
    'brzeszczę': 'MAŁOPOLSKIE',
    'libiąż': 'MAŁOPOLSKIE',
    'bukowno': 'MAŁOPOLSKIE',
    'dąbrowa tarnowska': 'MAŁOPOLSKIE',
    'brzesko': 'MAŁOPOLSKIE',
    'dobczyce': 'MAŁOPOLSKIE',
    'kalwaria zebrzydowska': 'MAŁOPOLSKIE',
    'rabka-zdrój': 'MAŁOPOLSKIE',
    'szczawnica': 'MAŁOPOLSKIE',
    'krynica-zdrój': 'MAŁOPOLSKIE',
    'muszyna': 'MAŁOPOLSKIE',
    'stary sącz': 'MAŁOPOLSKIE',
    'limanowa': 'MAŁOPOLSKIE',
    'jordanów': 'MAŁOPOLSKIE',
    'sucha beskidzka': 'MAŁOPOLSKIE',
    'żywiec': 'MAŁOPOLSKIE',
    'maków podhalański': 'MAŁOPOLSKIE',
    'alwernia': 'MAŁOPOLSKIE',
    'brzeszcze': 'MAŁOPOLSKIE',
    'grybów': 'MAŁOPOLSKIE',
    'mszana dolna': 'MAŁOPOLSKIE',
    'mogilany': 'MAŁOPOLSKIE',
    'libertów': 'MAŁOPOLSKIE',
    'grębałów': 'MAŁOPOLSKIE',
    # Krakow districts
    'bieńczyce': 'MAŁOPOLSKIE',
    'bieżanów': 'MAŁOPOLSKIE',
    'bieżanów- prokocim': 'MAŁOPOLSKIE',
    'borek fałęcki': 'MAŁOPOLSKIE',
    'bronowice': 'MAŁOPOLSKIE',
    'bronowice małe': 'MAŁOPOLSKIE',
    'bronowice wielkie': 'MAŁOPOLSKIE',
    'czerwony prądnik': 'MAŁOPOLSKIE',
    'czyżyny': 'MAŁOPOLSKIE',
    'dębniki': 'MAŁOPOLSKIE',
    'grzegórzki': 'MAŁOPOLSKIE',
    'mistrzejowice': 'MAŁOPOLSKIE',
    'mogiła': 'MAŁOPOLSKIE',
    'mydlniki': 'MAŁOPOLSKIE',

    # ŚLĄSKIE (Silesian Voivodeship) - Capital: Katowice
    'katowice': 'ŚLĄSKIE',
    'częstochowa': 'ŚLĄSKIE',
    'sosnowiec': 'ŚLĄSKIE',
    'gliwice': 'ŚLĄSKIE',
    'zabrze': 'ŚLĄSKIE',
    'bytom': 'ŚLĄSKIE',
    'ruda śląska': 'ŚLĄSKIE',
    'rybnik': 'ŚLĄSKIE',
    'tychy': 'ŚLĄSKIE',
    'dąbrowa górnicza': 'ŚLĄSKIE',
    'chorzów': 'ŚLĄSKIE',
    'jaworzno': 'ŚLĄSKIE',
    'jastrzębie-zdrój': 'ŚLĄSKIE',
    'mysłowice': 'ŚLĄSKIE',
    'siemianowice śląskie': 'ŚLĄSKIE',
    'piekary śląskie': 'ŚLĄSKIE',
    'będzin': 'ŚLĄSKIE',
    'tarnowskie góry': 'ŚLĄSKIE',
    'bielsko-biała': 'ŚLĄSKIE',
    'żory': 'ŚLĄSKIE',
    'czechowice-dziedzice': 'ŚLĄSKIE',
    'świętochłowice': 'ŚLĄSKIE',
    'zawiercie': 'ŚLĄSKIE',
    'wodzisław śląski': 'ŚLĄSKIE',
    'racibórz': 'ŚLĄSKIE',
    'żywiec': 'ŚLĄSKIE',
    'cieszyn': 'ŚLĄSKIE',
    'ustroń': 'ŚLĄSKIE',
    'wisła': 'ŚLĄSKIE',
    'skoczów': 'ŚLĄSKIE',
    'strumień': 'ŚLĄSKIE',
    'lubliniec': 'ŚLĄSKIE',
    'kłobuck': 'ŚLĄSKIE',
    'olesno': 'ŚLĄSKIE',
    'blachownia': 'ŚLĄSKIE',
    'czeladź': 'ŚLĄSKIE',
    'czerwionka-leszczyny': 'ŚLĄSKIE',
    'imielin': 'ŚLĄSKIE',
    'mikołów': 'ŚLĄSKIE',
    'orzesze': 'ŚLĄSKIE',
    'radlin': 'ŚLĄSKIE',
    'rydułtowy': 'ŚLĄSKIE',
    'wodzisław śląski': 'ŚLĄSKIE',
    'godów': 'ŚLĄSKIE',
    'giszowiec': 'ŚLĄSKIE',
    'brynów': 'ŚLĄSKIE',
    'muchowiec': 'ŚLĄSKIE',
    'janów-nikiszowiec': 'ŚLĄSKIE',
    'kantorowice': 'ŚLĄSKIE',
    'dąbrowa górna': 'ŚLĄSKIE',
    'godów mały': 'ŚLĄSKIE',

    # DOLNOŚLĄSKIE (Lower Silesian Voivodeship) - Capital: Wrocław
    'wrocław': 'DOLNOŚLĄSKIE',
    'wroclaw': 'DOLNOŚLĄSKIE',
    'wałbrzych': 'DOLNOŚLĄSKIE',
    'legnica': 'DOLNOŚLĄSKIE',
    'jelenia góra': 'DOLNOŚLĄSKIE',
    'głogów': 'DOLNOŚLĄSKIE',
    'lubin': 'DOLNOŚLĄSKIE',
    'bolesławiec': 'DOLNOŚLĄSKIE',
    'oleśnica': 'DOLNOŚLĄSKIE',
    'świdnica': 'DOLNOŚLĄSKIE',
    'zgorzelec': 'DOLNOŚLĄSKIE',
    'kłodzko': 'DOLNOŚLĄSKIE',
    'dzierżoniów': 'DOLNOŚLĄSKIE',
    'ząbkowice śląskie': 'DOLNOŚLĄSKIE',
    'bielawa': 'DOLNOŚLĄSKIE',
    'pieszyce': 'DOLNOŚLĄSKIE',
    'nowa ruda': 'DOLNOŚLĄSKIE',
    'bystrzyca kłodzka': 'DOLNOŚLĄSKIE',
    'lądek-zdrój': 'DOLNOŚLĄSKIE',
    'kłodzka': 'DOLNOŚLĄSKIE',
    'kamienna góra': 'DOLNOŚLĄSKIE',
    'kowary': 'DOLNOŚLĄSKIE',
    'szklarska poręba': 'DOLNOŚLĄSKIE',
    'karpacz': 'DOLNOŚLĄSKIE',
    'piechowice': 'DOLNOŚLĄSKIE',
    'lubań': 'DOLNOŚLĄSKIE',
    'świeradów-zdrój': 'DOLNOŚLĄSKIE',
    'lwówek śląski': 'DOLNOŚLĄSKIE',
    'gryfów śląski': 'DOLNOŚLĄSKIE',
    'mirsk': 'DOLNOŚLĄSKIE',
    'leśna': 'DOLNOŚLĄSKIE',
    'jawor': 'DOLNOŚLĄSKIE',
    'złotoryja': 'DOLNOŚLĄSKIE',
    'chojnów': 'DOLNOŚLĄSKIE',
    'przemków': 'DOLNOŚLĄSKIE',
    'góra': 'DOLNOŚLĄSKIE',
    'wołów': 'DOLNOŚLĄSKIE',
    'oława': 'DOLNOŚLĄSKIE',
    'brzeg dolny': 'DOLNOŚLĄSKIE',
    'strzegom': 'DOLNOŚLĄSKIE',
    'ząbkowice śląskie': 'DOLNOŚLĄSKIE',
    'ziębice': 'DOLNOŚLĄSKIE',
    'kąty wrocławskie': 'DOLNOŚLĄSKIE',
    'sobótka': 'DOLNOŚLĄSKIE',
    'środa śląska': 'DOLNOŚLĄSKIE',
    'trzebnica': 'DOLNOŚLĄSKIE',
    'żmigród': 'DOLNOŚLĄSKIE',
    'milicz': 'DOLNOŚLĄSKIE',
    'syców': 'DOLNOŚLĄSKIE',
    'namysłów': 'DOLNOŚLĄSKIE',
    'bierutów': 'DOLNOŚLĄSKIE',
    'polkowice': 'DOLNOŚLĄSKIE',
    'prochowice': 'DOLNOŚLĄSKIE',
    'chocianów': 'DOLNOŚLĄSKIE',
    'przemków': 'DOLNOŚLĄSKIE',
    'radwanice': 'DOLNOŚLĄSKIE',
    'węgliniec': 'DOLNOŚLĄSKIE',
    'bogatynia': 'DOLNOŚLĄSKIE',
    'pieńsk': 'DOLNOŚLĄSKIE',
    'boguszów-gorce': 'DOLNOŚLĄSKIE',
    'jedlina-zdrój': 'DOLNOŚLĄSKIE',
    'szczawno-zdrój': 'DOLNOŚLĄSKIE',
    'świebodzice': 'DOLNOŚLĄSKIE',
    'kłodzko': 'DOLNOŚLĄSKIE',
    'duszniki-zdrój': 'DOLNOŚLĄSKIE',
    'polanica-zdrój': 'DOLNOŚLĄSKIE',
    'kudowa-zdrój': 'DOLNOŚLĄSKIE',
    'radków': 'DOLNOŚLĄSKIE',
    'międzylesie': 'DOLNOŚLĄSKIE',
    'stronie śląskie': 'DOLNOŚLĄSKIE',
    'jelcz-laskowice': 'DOLNOŚLĄSKIE',
    'dobroszyce': 'DOLNOŚLĄSKIE',
    'prusice': 'DOLNOŚLĄSKIE',
    'twardogóra': 'DOLNOŚLĄSKIE',
    'rawicz': 'DOLNOŚLĄSKIE',
    'góra': 'DOLNOŚLĄSKIE',
    'sycow': 'DOLNOŚLĄSKIE',
    'oborniki śląskie': 'DOLNOŚLĄSKIE',
    'bielany wrocławskie': 'DOLNOŚLĄSKIE',
    'muchobór': 'DOLNOŚLĄSKIE',
    'muchobór mały': 'DOLNOŚLĄSKIE',
    'muchobór wielki': 'DOLNOŚLĄSKIE',
    'grabiszyn': 'DOLNOŚLĄSKIE',
    'grabiszynek': 'DOLNOŚLĄSKIE',
    'jagodno': 'DOLNOŚLĄSKIE',
    'fabryczna': 'DOLNOŚLĄSKIE',
    'gaj': 'DOLNOŚLĄSKIE',
    'karłowice': 'DOLNOŚLĄSKIE',
    'pawłowice': 'DOLNOŚLĄSKIE',
    'żerniki': 'DOLNOŚLĄSKIE',

    # WIELKOPOLSKIE (Greater Poland Voivodeship) - Capital: Poznań
    'poznań': 'WIELKOPOLSKIE',
    'poznan': 'WIELKOPOLSKIE',
    'kalisz': 'WIELKOPOLSKIE',
    'konin': 'WIELKOPOLSKIE',
    'piła': 'WIELKOPOLSKIE',
    'ostrów wielkopolski': 'WIELKOPOLSKIE',
    'gniezno': 'WIELKOPOLSKIE',
    'leszno': 'WIELKOPOLSKIE',
    'turek': 'WIELKOPOLSKIE',
    'września': 'WIELKOPOLSKIE',
    'krotoszyn': 'WIELKOPOLSKIE',
    'jarocin': 'WIELKOPOLSKIE',
    'rawicz': 'WIELKOPOLSKIE',
    'śrem': 'WIELKOPOLSKIE',
    'gostyń': 'WIELKOPOLSKIE',
    'wolsztyn': 'WIELKOPOLSKIE',
    'nowy tomyśl': 'WIELKOPOLSKIE',
    'kościan': 'WIELKOPOLSKIE',
    'swarzędz': 'WIELKOPOLSKIE',
    'luboń': 'WIELKOPOLSKIE',
    'mosina': 'WIELKOPOLSKIE',
    'puszczykowo': 'WIELKOPOLSKIE',
    'kostrzyn': 'WIELKOPOLSKIE',
    'środa wielkopolska': 'WIELKOPOLSKIE',
    'kórnik': 'WIELKOPOLSKIE',
    'czerwonak': 'WIELKOPOLSKIE',
    'tarnowo podgórne': 'WIELKOPOLSKIE',
    'dopiewo': 'WIELKOPOLSKIE',
    'murowana goślina': 'WIELKOPOLSKIE',
    'wielichowo': 'WIELKOPOLSKIE',
    'grodzisk wielkopolski': 'WIELKOPOLSKIE',
    'wolsztyn': 'WIELKOPOLSKIE',
    'kąkolewo': 'WIELKOPOLSKIE',
    'krzyż wielkopolski': 'WIELKOPOLSKIE',
    'czarnków': 'WIELKOPOLSKIE',
    'chodzież': 'WIELKOPOLSKIE',
    'wągrowiec': 'WIELKOPOLSKIE',
    'szamotuły': 'WIELKOPOLSKIE',
    'międzychód': 'WIELKOPOLSKIE',
    'słupca': 'WIELKOPOLSKIE',
    'koło': 'WIELKOPOLSKIE',
    'sompolno': 'WIELKOPOLSKIE',
    'dąbie': 'WIELKOPOLSKIE',
    'janowiec wielkopolski': 'WIELKOPOLSKIE',
    'czempiń': 'WIELKOPOLSKIE',
    'brodnica': 'WIELKOPOLSKIE',
    'lutynia': 'WIELKOPOLSKIE',
    'iwiny': 'WIELKOPOLSKIE',
    'górczyn': 'WIELKOPOLSKIE',
    'grunwald': 'WIELKOPOLSKIE',

    # POMORSKIE (Pomeranian Voivodeship) - Capital: Gdańsk
    'gdańsk': 'POMORSKIE',
    'gdansk': 'POMORSKIE',
    'gdynia': 'POMORSKIE',
    'słupsk': 'POMORSKIE',
    'sopot': 'POMORSKIE',
    'tczew': 'POMORSKIE',
    'starogard gdański': 'POMORSKIE',
    'wejherowo': 'POMORSKIE',
    'rumia': 'POMORSKIE',
    'pruszcz gdański': 'POMORSKIE',
    'reda': 'POMORSKIE',
    'kartuzy': 'POMORSKIE',
    'lębork': 'POMORSKIE',
    'puck': 'POMORSKIE',
    'malbork': 'POMORSKIE',
    'kościerzyna': 'POMORSKIE',
    'chojnice': 'POMORSKIE',
    'człuchów': 'POMORSKIE',
    'bytów': 'POMORSKIE',
    'ustka': 'POMORSKIE',
    'łeba': 'POMORSKIE',
    'władysławowo': 'POMORSKIE',
    'jastarnia': 'POMORSKIE',
    'hel': 'POMORSKIE',
    'krynica morska': 'POMORSKIE',
    'sztutowo': 'POMORSKIE',
    'nowy dwór gdański': 'POMORSKIE',
    'kwidzyn': 'POMORSKIE',
    'prabuty': 'POMORSKIE',
    'dzierzgoń': 'POMORSKIE',
    'sztum': 'POMORSKIE',
    'gniew': 'POMORSKIE',
    'pelplin': 'POMORSKIE',
    'skórcz': 'POMORSKIE',
    'tczew': 'POMORSKIE',
    'pszczółki': 'POMORSKIE',
    'subkowy': 'POMORSKIE',
    'banino': 'POMORSKIE',
    'żukowo': 'POMORSKIE',
    'kolbudy': 'POMORSKIE',
    'przywidz': 'POMORSKIE',
    'cedry wielkie': 'POMORSKIE',
    'godziszewo': 'POMORSKIE',
    'bojano': 'POMORSKIE',
    'sierakowice': 'POMORSKIE',
    'sulęczyno': 'POMORSKIE',
    'żukowo': 'POMORSKIE',
    'somonino': 'POMORSKIE',
    'chmielno': 'POMORSKIE',
    'przywidz': 'POMORSKIE',
    'gdańsk-kokoszki': 'POMORSKIE',
    'jelitkowo': 'POMORSKIE',
    'mały kack': 'POMORSKIE',
    'borkowo łostowickie': 'POMORSKIE',

    # LUBELSKIE (Lublin Voivodeship) - Capital: Lublin
    'lublin': 'LUBELSKIE',
    'zamość': 'LUBELSKIE',
    'chełm': 'LUBELSKIE',
    'chelm': 'LUBELSKIE',
    'biała podlaska': 'LUBELSKIE',
    'puławy': 'LUBELSKIE',
    'świdnik': 'LUBELSKIE',
    'kraśnik': 'LUBELSKIE',
    'łuków': 'LUBELSKIE',
    'tomaszów lubelski': 'LUBELSKIE',
    'hrubieszów': 'LUBELSKIE',
    'lubartów': 'LUBELSKIE',
    'parczew': 'LUBELSKIE',
    'łęczna': 'LUBELSKIE',
    'międzyrzec podlaski': 'LUBELSKIE',
    'radzyń podlaski': 'LUBELSKIE',
    'włodawa': 'LUBELSKIE',
    'terespol': 'LUBELSKIE',
    'kodeń': 'LUBELSKIE',
    'janów lubelski': 'LUBELSKIE',
    'frampol': 'LUBELSKIE',
    'zwierzyniec': 'LUBELSKIE',
    'szczebrzeszyn': 'LUBELSKIE',
    'krasnystaw': 'LUBELSKIE',
    'rejowiec fabryczny': 'LUBELSKIE',
    'sawin': 'LUBELSKIE',
    'dorohusk': 'LUBELSKIE',
    'horodło': 'LUBELSKIE',
    'bełżyce': 'LUBELSKIE',
    'nałęczów': 'LUBELSKIE',
    'końskowola': 'LUBELSKIE',
    'opole lubelskie': 'LUBELSKIE',
    'poniatowa': 'LUBELSKIE',
    'kazimierz dolny': 'LUBELSKIE',
    'ryki': 'LUBELSKIE',
    'dęblin': 'LUBELSKIE',
    'garbabia': 'LUBELSKIE',

    # ZACHODNIOPOMORSKIE (West Pomeranian Voivodeship) - Capital: Szczecin
    'szczecin': 'ZACHODNIOPOMORSKIE',
    'koszalin': 'ZACHODNIOPOMORSKIE',
    'stargard': 'ZACHODNIOPOMORSKIE',
    'kołobrzeg': 'ZACHODNIOPOMORSKIE',
    'świnoujście': 'ZACHODNIOPOMORSKIE',
    'wałcz': 'ZACHODNIOPOMORSKIE',
    'białogard': 'ZACHODNIOPOMORSKIE',
    'szczecinek': 'ZACHODNIOPOMORSKIE',
    'goleniów': 'ZACHODNIOPOMORSKIE',
    'gryfino': 'ZACHODNIOPOMORSKIE',
    'police': 'ZACHODNIOPOMORSKIE',
    'kamień pomorski': 'ZACHODNIOPOMORSKIE',
    'gryfice': 'ZACHODNIOPOMORSKIE',
    'choszczno': 'ZACHODNIOPOMORSKIE',
    'nowogard': 'ZACHODNIOPOMORSKIE',
    'darłowo': 'ZACHODNIOPOMORSKIE',
    'trzebiatów': 'ZACHODNIOPOMORSKIE',
    'świdwin': 'ZACHODNIOPOMORSKIE',
    'międzyzdroje': 'ZACHODNIOPOMORSKIE',
    'dobra szczecińska': 'ZACHODNIOPOMORSKIE',
    'myślibórz': 'ZACHODNIOPOMORSKIE',
    'barlinek': 'ZACHODNIOPOMORSKIE',
    'dębno': 'ZACHODNIOPOMORSKIE',
    'chojna': 'ZACHODNIOPOMORSKIE',
    'trzcińsko-zdrój': 'ZACHODNIOPOMORSKIE',
    'cedynia': 'ZACHODNIOPOMORSKIE',
    'moryń': 'ZACHODNIOPOMORSKIE',
    'mieszkowice': 'ZACHODNIOPOMORSKIE',
    'widuchowa': 'ZACHODNIOPOMORSKIE',
    'nowe warpno': 'ZACHODNIOPOMORSKIE',
    'stepnica': 'ZACHODNIOPOMORSKIE',
    'dziwnów': 'ZACHODNIOPOMORSKIE',
    'wolin': 'ZACHODNIOPOMORSKIE',
    'lubin': 'ZACHODNIOPOMORSKIE',
    'resko': 'ZACHODNIOPOMORSKIE',
    'łobez': 'ZACHODNIOPOMORSKIE',
    'płoty': 'ZACHODNIOPOMORSKIE',
    'gościno': 'ZACHODNIOPOMORSKIE',
    'sławno': 'ZACHODNIOPOMORSKIE',
    'postomino': 'ZACHODNIOPOMORSKIE',
    'ustka': 'ZACHODNIOPOMORSKIE',
    'miastko': 'ZACHODNIOPOMORSKIE',
    'człopa': 'ZACHODNIOPOMORSKIE',
    'tuczno': 'ZACHODNIOPOMORSKIE',
    'mirosławiec': 'ZACHODNIOPOMORSKIE',
    'wałcz': 'ZACHODNIOPOMORSKIE',
    'czaplinek': 'ZACHODNIOPOMORSKIE',
    'złocieniec': 'ZACHODNIOPOMORSKIE',
    'drawsko pomorskie': 'ZACHODNIOPOMORSKIE',
    'połczyn-zdrój': 'ZACHODNIOPOMORSKIE',
    'świdwin': 'ZACHODNIOPOMORSKIE',
    'łobez': 'ZACHODNIOPOMORSKIE',
    'radowo małe': 'ZACHODNIOPOMORSKIE',
    'karlino': 'ZACHODNIOPOMORSKIE',
    'barwice': 'ZACHODNIOPOMORSKIE',
    'borne sulinowo': 'ZACHODNIOPOMORSKIE',
    'maszewo': 'ZACHODNIOPOMORSKIE',
    'golczewo': 'ZACHODNIOPOMORSKIE',
    'chociwel': 'ZACHODNIOPOMORSKIE',
    'lipiany': 'ZACHODNIOPOMORSKIE',
    'bożepole': 'ZACHODNIOPOMORSKIE',
    'choszczówka': 'ZACHODNIOPOMORSKIE',
    'drawno': 'ZACHODNIOPOMORSKIE',
    'debrzno': 'ZACHODNIOPOMORSKIE',

    # PODLASKIE (Podlaskie Voivodeship) - Capital: Białystok
    'białystok': 'PODLASKIE',
    'bialystok': 'PODLASKIE',
    'łomża': 'PODLASKIE',
    'lomza': 'PODLASKIE',
    'suwałki': 'PODLASKIE',
    'suwalki': 'PODLASKIE',
    'augustów': 'PODLASKIE',
    'bielsk podlaski': 'PODLASKIE',
    'grajewo': 'PODLASKIE',
    'wysokie mazowieckie': 'PODLASKIE',
    'zambrów': 'PODLASKIE',
    'hajnówka': 'PODLASKIE',
    'siemiatycze': 'PODLASKIE',
    'drohiczyn': 'PODLASKIE',
    'czarna białostocka': 'PODLASKIE',
    'ciechanowiec': 'PODLASKIE',
    'wasilków': 'PODLASKIE',
    'supraśl': 'PODLASKIE',
    'michałowo': 'PODLASKIE',
    'krynki': 'PODLASKIE',
    'goniądz': 'PODLASKIE',
    'jedwabne': 'PODLASKIE',
    'choroszcz': 'PODLASKIE',
    'tykocin': 'PODLASKIE',
    'dąbrowa białostocka': 'PODLASKIE',
    'łapy': 'PODLASKIE',
    'turośń kościelna': 'PODLASKIE',
    'poświętne': 'PODLASKIE',
    'boćki': 'PODLASKIE',
    'brańsk': 'PODLASKIE',
    'rudka': 'PODLASKIE',
    'czyże': 'PODLASKIE',
    'narewka': 'PODLASKIE',
    'dubicze cerkiewne': 'PODLASKIE',
    'kleszczele': 'PODLASKIE',
    'orla': 'PODLASKIE',
    'czeremcha': 'PODLASKIE',
    'nurzec-stacja': 'PODLASKIE',
    'milejczyce': 'PODLASKIE',
    'korycin': 'PODLASKIE',
    'krynki': 'PODLASKIE',
    'sokółka': 'PODLASKIE',
    'dąbrowa białostocka': 'PODLASKIE',

    # KUJAWSKO-POMORSKIE (Kuyavian-Pomeranian Voivodeship) - Capital: Bydgoszcz
    'bydgoszcz': 'KUJAWSKO-POMORSKIE',
    'toruń': 'KUJAWSKO-POMORSKIE',
    'torun': 'KUJAWSKO-POMORSKIE',
    'włocławek': 'KUJAWSKO-POMORSKIE',
    'wloclawek': 'KUJAWSKO-POMORSKIE',
    'grudziądz': 'KUJAWSKO-POMORSKIE',
    'inowrocław': 'KUJAWSKO-POMORSKIE',
    'świecie': 'KUJAWSKO-POMORSKIE',
    'żnin': 'KUJAWSKO-POMORSKIE',
    'nakło nad notecią': 'KUJAWSKO-POMORSKIE',
    'tuchola': 'KUJAWSKO-POMORSKIE',
    'golub-dobrzyń': 'KUJAWSKO-POMORSKIE',
    'aleksandrów kujawski': 'KUJAWSKO-POMORSKIE',
    'ciechocinek': 'KUJAWSKO-POMORSKIE',
    'kowal': 'KUJAWSKO-POMORSKIE',
    'kruszwica': 'KUJAWSKO-POMORSKIE',
    'radziejów': 'KUJAWSKO-POMORSKIE',
    'piotrków kujawski': 'KUJAWSKO-POMORSKIE',
    'strzelno': 'KUJAWSKO-POMORSKIE',
    'mogilno': 'KUJAWSKO-POMORSKIE',
    'janikowo': 'KUJAWSKO-POMORSKIE',
    'pakość': 'KUJAWSKO-POMORSKIE',
    'szubin': 'KUJAWSKO-POMORSKIE',
    'kcynia': 'KUJAWSKO-POMORSKIE',
    'barcin': 'KUJAWSKO-POMORSKIE',
    'janowiec wielkopolski': 'KUJAWSKO-POMORSKIE',
    'sępólno krajeńskie': 'KUJAWSKO-POMORSKIE',
    'więcbork': 'KUJAWSKO-POMORSKIE',
    'kamień krajeński': 'KUJAWSKO-POMORSKIE',
    'łabiszyn': 'KUJAWSKO-POMORSKIE',
    'solec kujawski': 'KUJAWSKO-POMORSKIE',
    'brodnica': 'KUJAWSKO-POMORSKIE',
    'jabłonowo pomorskie': 'KUJAWSKO-POMORSKIE',
    'fordon': 'KUJAWSKO-POMORSKIE',
    'chełmno': 'KUJAWSKO-POMORSKIE',
    'chełmża': 'KUJAWSKO-POMORSKIE',

    # WARMIŃSKO-MAZURSKIE (Warmian-Masurian Voivodeship) - Capital: Olsztyn
    'olsztyn': 'WARMIŃSKO-MAZURSKIE',
    'elbląg': 'WARMIŃSKO-MAZURSKIE',
    'ełk': 'WARMIŃSKO-MAZURSKIE',
    'elk': 'WARMIŃSKO-MAZURSKIE',
    'ostróda': 'WARMIŃSKO-MAZURSKIE',
    'iława': 'WARMIŃSKO-MAZURSKIE',
    'kętrzyn': 'WARMIŃSKO-MAZURSKIE',
    'giżycko': 'WARMIŃSKO-MAZURSKIE',
    'szczytno': 'WARMIŃSKO-MAZURSKIE',
    'braniewo': 'WARMIŃSKO-MAZURSKIE',
    'lidzbark warmiński': 'WARMIŃSKO-MAZURSKIE',
    'bartoszyce': 'WARMIŃSKO-MAZURSKIE',
    'węgorzewo': 'WARMIŃSKO-MAZURSKIE',
    'mrągowo': 'WARMIŃSKO-MAZURSKIE',
    'nidzica': 'WARMIŃSKO-MAZURSKIE',
    'działdowo': 'WARMIŃSKO-MAZURSKIE',
    'pisz': 'WARMIŃSKO-MAZURSKIE',
    'ruciane-nida': 'WARMIŃSKO-MAZURSKIE',
    'mikołajki': 'WARMIŃSKO-MAZURSKIE',
    'orzysz': 'WARMIŃSKO-MAZURSKIE',
    'biała piska': 'WARMIŃSKO-MAZURSKIE',
    'pasłęk': 'WARMIŃSKO-MAZURSKIE',
    'tolkmicko': 'WARMIŃSKO-MAZURSKIE',
    'fromborg': 'WARMIŃSKO-MAZURSKIE',
    'morąg': 'WARMIŃSKO-MAZURSKIE',
    'dobre miasto': 'WARMIŃSKO-MAZURSKIE',
    'lidzbark': 'WARMIŃSKO-MAZURSKIE',
    'orneta': 'WARMIŃSKO-MAZURSKIE',
    'jeziorany': 'WARMIŃSKO-MAZURSKIE',
    'barczewo': 'WARMIŃSKO-MAZURSKIE',
    'bisztynek': 'WARMIŃSKO-MAZURSKIE',
    'reszel': 'WARMIŃSKO-MAZURSKIE',
    'korsze': 'WARMIŃSKO-MAZURSKIE',
    'gołdap': 'WARMIŃSKO-MAZURSKIE',
    'olecko': 'WARMIŃSKO-MAZURSKIE',
    'sępopol': 'WARMIŃSKO-MAZURSKIE',
    'górowo iławeckie': 'WARMIŃSKO-MAZURSKIE',
    'miłomłyn': 'WARMIŃSKO-MAZURSKIE',
    'biskupiec': 'WARMIŃSKO-MAZURSKIE',

    # ŁÓDZKIE (Łódź Voivodeship) - Capital: Łódź
    'łódź': 'ŁÓDZKIE',
    'lodz': 'ŁÓDZKIE',
    'piotrków trybunalski': 'ŁÓDZKIE',
    'pabianice': 'ŁÓDZKIE',
    'tomaszów mazowiecki': 'ŁÓDZKIE',
    'bełchatów': 'ŁÓDZKIE',
    'skierniewice': 'ŁÓDZKIE',
    'zgierz': 'ŁÓDZKIE',
    'radomsko': 'ŁÓDZKIE',
    'wieluń': 'ŁÓDZKIE',
    'zduńska wola': 'ŁÓDZKIE',
    'sieradz': 'ŁÓDZKIE',
    'kutno': 'ŁÓDZKIE',
    'pajęczno': 'ŁÓDZKIE',
    'łask': 'ŁÓDZKIE',
    'brzeziny': 'ŁÓDZKIE',
    'głowno': 'ŁÓDZKIE',
    'ozorków': 'ŁÓDZKIE',
    'łęczyca': 'ŁÓDZKIE',
    'poddębice': 'ŁÓDZKIE',
    'wieruszów': 'ŁÓDZKIE',
    'łaski': 'ŁÓDZKIE',
    'aleksandrów łódzki': 'ŁÓDZKIE',
    'konstantynów łódzki': 'ŁÓDZKIE',
    'andrespol': 'ŁÓDZKIE',
    'stryków': 'ŁÓDZKIE',
    'tuszyn': 'ŁÓDZKIE',
    'rzgów': 'ŁÓDZKIE',
    'brójce': 'ŁÓDZKIE',
    'nowosolna': 'ŁÓDZKIE',
    'łowicz': 'ŁÓDZKIE',
    'błaszki': 'ŁÓDZKIE',
    'chodecz': 'ŁÓDZKIE',
    'działoszyn': 'ŁÓDZKIE',
    'gorzów wielkopolski': 'ŁÓDZKIE',
    'aleksandrów': 'ŁÓDZKIE',
    'garbatka': 'ŁÓDZKIE',
    'florentynów': 'ŁÓDZKIE',
    'garnizo': 'ŁÓDZKIE',
    'garnizon': 'ŁÓDZKIE',
    'karolew': 'ŁÓDZKIE',
    'karolin': 'ŁÓDZKIE',
    'mateczny': 'ŁÓDZKIE',

    # ŚWIĘTOKRZYSKIE (Holy Cross Voivodeship) - Capital: Kielce
    'kielce': 'ŚWIĘTOKRZYSKIE',
    'ostrowiec świętokrzyski': 'ŚWIĘTOKRZYSKIE',
    'starachowice': 'ŚWIĘTOKRZYSKIE',
    'sandomierz': 'ŚWIĘTOKRZYSKIE',
    'skarżysko-kamienna': 'ŚWIĘTOKRZYSKIE',
    'końskie': 'ŚWIĘTOKRZYSKIE',
    'jędrzejów': 'ŚWIĘTOKRZYSKIE',
    'busko-zdrój': 'ŚWIĘTOKRZYSKIE',
    'kazimierza wielka': 'ŚWIĘTOKRZYSKIE',
    'pińczów': 'ŚWIĘTOKRZYSKIE',
    'staszów': 'ŚWIĘTOKRZYSKIE',
    'małogoszcz': 'ŚWIĘTOKRZYSKIE',
    'połaniec': 'ŚWIĘTOKRZYSKIE',
    'chmielnik': 'ŚWIĘTOKRZYSKIE',
    'solec-zdrój': 'ŚWIĘTOKRZYSKIE',
    'opatów': 'ŚWIĘTOKRZYSKIE',
    'ożarów': 'ŚWIĘTOKRZYSKIE',
    'skalbmierz': 'ŚWIĘTOKRZYSKIE',
    'działoszyce': 'ŚWIĘTOKRZYSKIE',
    'kunów': 'ŚWIĘTOKRZYSKIE',
    'suchedniów': 'ŚWIĘTOKRZYSKIE',
    'daleszyce': 'ŚWIĘTOKRZYSKIE',
    'bodzentyn': 'ŚWIĘTOKRZYSKIE',
    'chęciny': 'ŚWIĘTOKRZYSKIE',
    'piekoszów': 'ŚWIĘTOKRZYSKIE',
    'morawica': 'ŚWIĘTOKRZYSKIE',
    'miedziana góra': 'ŚWIĘTOKRZYSKIE',
    'górno': 'ŚWIĘTOKRZYSKIE',
    'sitkówka-nowiny': 'ŚWIĘTOKRZYSKIE',
    'strawczyn': 'ŚWIĘTOKRZYSKIE',

    # PODKARPACKIE (Subcarpathian Voivodeship) - Capital: Rzeszów
    'rzeszów': 'PODKARPACKIE',
    'rzeszow': 'PODKARPACKIE',
    'przemyśl': 'PODKARPACKIE',
    'stalowa wola': 'PODKARPACKIE',
    'tarnobrzeg': 'PODKARPACKIE',
    'krosno': 'PODKARPACKIE',
    'mielec': 'PODKARPACKIE',
    'jasło': 'PODKARPACKIE',
    'sanok': 'PODKARPACKIE',
    'jarosław': 'PODKARPACKIE',
    'dębica': 'PODKARPACKIE',
    'łańcut': 'PODKARPACKIE',
    'brzozów': 'PODKARPACKIE',
    'ropczyce': 'PODKARPACKIE',
    'strzyżów': 'PODKARPACKIE',
    'przeworsk': 'PODKARPACKIE',
    'leżajsk': 'PODKARPACKIE',
    'nisko': 'PODKARPACKIE',
    'rudnik nad sanem': 'PODKARPACKIE',
    'kolbuszowa': 'PODKARPACKIE',
    'głogów małopolski': 'PODKARPACKIE',
    'tyczyn': 'PODKARPACKIE',
    'boguchwała': 'PODKARPACKIE',
    'lesko': 'PODKARPACKIE',
    'ustrzyki dolne': 'PODKARPACKIE',
    'lubaczów': 'PODKARPACKIE',
    'radymno': 'PODKARPACKIE',
    'zagórz': 'PODKARPACKIE',
    'solina': 'PODKARPACKIE',
    'cisna': 'PODKARPACKIE',
    'wetlina': 'PODKARPACKIE',
    'ustrzyki górne': 'PODKARPACKIE',
    'baligród': 'PODKARPACKIE',

    # OPOLSKIE (Opole Voivodeship) - Capital: Opole
    'opole': 'OPOLSKIE',
    'kędzierzyn-koźle': 'OPOLSKIE',
    'nysa': 'OPOLSKIE',
    'brzeg': 'OPOLSKIE',
    'kluczbork': 'OPOLSKIE',
    'prudnik': 'OPOLSKIE',
    'krapkowice': 'OPOLSKIE',
    'głubczyce': 'OPOLSKIE',
    'strzelce opolskie': 'OPOLSKIE',
    'zawadzkie': 'OPOLSKIE',
    'zdzieszowice': 'OPOLSKIE',
    'lewin brzeski': 'OPOLSKIE',
    'grodków': 'OPOLSKIE',
    'niemodlin': 'OPOLSKIE',
    'olesno': 'OPOLSKIE',
    'praszka': 'OPOLSKIE',
    'kolonowskie': 'OPOLSKIE',
    'gogolin': 'OPOLSKIE',
    'kamień śląski': 'OPOLSKIE',
    'byczyna': 'OPOLSKIE',
    'namysłów': 'OPOLSKIE',
    'wolczyn': 'OPOLSKIE',

    # LUBUSKIE (Lubusz Voivodeship) - Capital: Gorzów Wielkopolski and Zielona Góra
    'gorzów wielkopolski': 'LUBUSKIE',
    'zielona góra': 'LUBUSKIE',
    'zielona gora': 'LUBUSKIE',
    'żary': 'LUBUSKIE',
    'nowa sól': 'LUBUSKIE',
    'żagań': 'LUBUSKIE',
    'świebodzin': 'LUBUSKIE',
    'międzyrzecz': 'LUBUSKIE',
    'sulechów': 'LUBUSKIE',
    'gubin': 'LUBUSKIE',
    'kostrzyn nad odrą': 'LUBUSKIE',
    'krosno odrzańskie': 'LUBUSKIE',
    'słubice': 'LUBUSKIE',
    'cybinka': 'LUBUSKIE',
    'rzepin': 'LUBUSKIE',
    'strzelce krajeńskie': 'LUBUSKIE',
    'gorzów wlkp.': 'LUBUSKIE',
    'drezdenko': 'LUBUSKIE',
    'skwierzyna': 'LUBUSKIE',
    'santok': 'LUBUSKIE',
    'witnica': 'LUBUSKIE',
    'górzyca': 'LUBUSKIE',
    'słońsk': 'LUBUSKIE',
    'deszczno': 'LUBUSKIE',
    'bogdaniec': 'LUBUSKIE',
    'myślibórz': 'LUBUSKIE',
    'chojna': 'LUBUSKIE',
    'trzcianka': 'LUBUSKIE',
    'czarnków': 'LUBUSKIE',
    'wieleń': 'LUBUSKIE',
    'drawno': 'LUBUSKIE',
    'babimost': 'LUBUSKIE',
    'kargowa': 'LUBUSKIE',
    'bojadła': 'LUBUSKIE',
    'zbąszynek': 'LUBUSKIE',
    'małomice': 'LUBUSKIE',
    'czerwieńsk': 'LUBUSKIE',
    'bytom odrzański': 'LUBUSKIE',
    'sława': 'LUBUSKIE',
    'szprotawa': 'LUBUSKIE',
    'przemków': 'LUBUSKIE',
    'niegosławice': 'LUBUSKIE',
    'dobiegniew': 'LUBUSKIE',
    'lubsko': 'LUBUSKIE',
    'żagań': 'LUBUSKIE',
    'iłowa': 'LUBUSKIE',
    'nowogród bobrzański': 'LUBUSKIE',
    'zagan': 'LUBUSKIE',
    'burdąg': 'LUBUSKIE',
    'bukowiec': 'LUBUSKIE',

    # Additional mappings for variations and common misspellings
    'czestochowa': 'ŚLĄSKIE',
    'wroclaw': 'DOLNOŚLĄSKIE',
    'poznan': 'WIELKOPOLSKIE',
    'gdansk': 'POMORSKIE',
    'gdynia': 'POMORSKIE',
    'gdansk-kokoszki': 'POMORSKIE',
    'gorzów wlkp.': 'LUBUSKIE',
    'wloclawek': 'KUJAWSKO-POMORSKIE',
    'bialystok': 'PODLASKIE',
    'lomza': 'PODLASKIE',
    'suwalki': 'PODLASKIE',
    'elk': 'WARMIŃSKO-MAZURSKIE',
    'rzeszow': 'PODKARPACKIE',
    'chelm': 'LUBELSKIE',
    'lodz': 'ŁÓDZKIE',
    'dabrowa gornicza': 'ŚLĄSKIE',
    'myslowice': 'ŚLĄSKIE',
    'chorzow': 'ŚLĄSKIE',
    'jastrz\u0119bie-zdroj': 'ŚLĄSKIE',
    'zory': 'ŚLĄSKIE',
    'ruda slaska': 'ŚLĄSKIE',
    'siemianowice slaskie': 'ŚLĄSKIE',
    'piekary slaskie': 'ŚLĄSKIE',
    'swietochlowice': 'ŚLĄSKIE',
    'torun': 'KUJAWSKO-POMORSKIE',
    'slupsk': 'POMORSKIE',
    'zielona gora': 'LUBUSKIE',

    # Special administrative names and regions
    'k-ce': 'ŚLĄSKIE',  # Abbreviation for Katowice area
    'miasteczko śląska': 'ŚLĄSKIE',
    'gądów': 'ŚLĄSKIE',
    'gądów mały': 'ŚLĄSKIE',
    'bytnik': 'ŚLĄSKIE',
    'bąkowo': 'POMORSKIE',
    'bażantowo': 'ZACHODNIOPOMORSKIE',
    'biały kamień': 'MAŁOPOLSKIE',
    'bieńkowice': 'MAZOWIECKIE',
    'bliżyn': 'ŚWIĘTOKRZYSKIE',
    'boleń': 'DOLNOŚLĄSKIE',
    'borek': 'ŚLĄSKIE',
    'bratoszewice': 'ŁÓDZKIE',
    'brochów': 'MAZOWIECKIE',
    'brętowo': 'POMORSKIE',
    'bąkowo': 'POMORSKIE',
    'cząstkowo': 'POMORSKIE',
    'czyżemin': 'MAZOWIECKIE',
    'dobrzykowice': 'DOLNOŚLĄSKIE',
    'elsnerów': 'ŁÓDZKIE',
    'glincz': 'ZACHODNIOPOMORSKIE',
    'gołąbki': 'ZACHODNIOPOMORSKIE',
    'grabieniec': 'DOLNOŚLĄSKIE',
    'grzmucin': 'MAŁOPOLSKIE',
    'grzymalitów': 'MAZOWIECKIE',
    'góraszka': 'MAZOWIECKIE',
    'górce': 'MAZOWIECKIE',
    'górka narodowa': 'MAZOWIECKIE',
    'górna': 'DOLNOŚLĄSKIE',
    'górniak': 'MAZOWIECKIE',
    'henryków': 'DOLNOŚLĄSKIE',
    'huta': 'MAZOWIECKIE',
    'jarkowice': 'DOLNOŚLĄSKIE',
    'jasień': 'ZACHODNIOPOMORSKIE',
    'jastrzębia': 'POMORSKIE',
    'jastrzębia góra': 'POMORSKIE',
    'jerzmanowo': 'ZACHODNIOPOMORSKIE',
    'jerzmanów': 'ZACHODNIOPOMORSKIE',
    'jeziorki': 'MAZOWIECKIE',
    'letnica': 'WIELKOPOLSKIE',
    'ligota': 'ŚLĄSKIE',
    'lipa piotrowska': 'ŁÓDZKIE',
    'majdan': 'LUBELSKIE',
    'marszowice': 'DOLNOŚLĄSKIE',
    'michałowice': 'MAŁOPOLSKIE',
    'michałów grabina': 'ŁÓDZKIE',
    'mirów': 'ŚLĄSKIE',
    'mokronos dolny': 'DOLNOŚLĄSKIE',
    'mrocza': 'KUJAWSKO-POMORSKIE',
    'murów': 'MAZOWIECKIE',
    'pawłowice': 'ŚLĄSKIE',
    'rusiec': 'ŁÓDZKIE',
    'sobuczyna': 'POMORSKIE',
    'tychy': 'ŚLĄSKIE',
    'wisła': 'ŚLĄSKIE',
    'żerniki': 'DOLNOŚLĄSKIE'
}

# Create normalized mappings (remove Polish diacritics for better matching)
def create_normalized_mapping():
    """Create a normalized version of the mapping with Polish diacritics removed."""
    polish_chars_map = {
        'ą': 'a', 'ć': 'c', 'ę': 'e', 'ł': 'l', 'ń': 'n',
        'ó': 'o', 'ś': 's', 'ź': 'z', 'ż': 'z'
    }
    
    normalized_mapping = {}
    
    for city, voivodeship in CITY_TO_VOIVODESHIP.items():
        # Add original mapping
        normalized_mapping[city.lower()] = voivodeship
        
        # Create normalized version
        normalized_city = city.lower()
        for polish_char, latin_char in polish_chars_map.items():
            normalized_city = normalized_city.replace(polish_char, latin_char)
        
        # Add normalized mapping if different from original
        if normalized_city != city.lower():
            normalized_mapping[normalized_city] = voivodeship
    
    return normalized_mapping

# Get the complete mapping including normalized versions
def get_complete_city_mapping():
    """Get the complete city mapping including normalized versions."""
    complete_mapping = CITY_TO_VOIVODESHIP.copy()
    normalized_mapping = create_normalized_mapping()
    complete_mapping.update(normalized_mapping)
    return complete_mapping

# Function to get voivodeship for a city
def get_voivodeship_for_city(city_name):
    """
    Get the voivodeship for a given city name.
    
    Args:
        city_name (str): Name of the city
        
    Returns:
        str: Voivodeship name or None if not found
    """
    if not city_name:
        return None
    
    complete_mapping = get_complete_city_mapping()
    city_normalized = city_name.lower().strip()
    
    return complete_mapping.get(city_normalized)
