COLUMN_MAPPINGS = {
    'apartment_prices': { # 195k+ records
        'city': 'city',
        'type': 'property_type',
        'squareMeters': 'area_sqm',
        'rooms': 'rooms',
        'floor': 'floor',
        'floorCount': 'floor_count',
        'buildYear': 'build_year',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'centreDistance': 'distance_to_center',
        'poiCount': 'poi_count',
        'schoolDistance': 'distance_to_school',
        'clinicDistance': 'distance_to_healthcare',
        'postOfficeDistance': 'distance_to_post_office',
        'kindergartenDistance': 'distance_to_kindergarten',
        'restaurantDistance': 'distance_to_restaurant',
        'collegeDistance': 'distance_to_college',
        'pharmacyDistance': 'distance_to_pharmacy',
        'ownership': 'ownership_type',
        'buildingMaterial': 'building_material',
        'condition': 'condition',
        'hasParkingSpace': 'has_parking',
        'hasBalcony': 'has_balcony',
        'hasElevator': 'has_elevator',
        'hasSecurity': 'has_security',
        'hasStorageRoom': 'has_storage',
        'price': 'price',
        'year': 'listing_year',
        'month': 'listing_month'
    },
    'house_prices': { # 20k+ records
        'address': 'address',
        'city': 'city',
        'floor': 'floor',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'price': 'price',
        'rooms': 'rooms',
        'sq': 'area_sqm',
        'build_year': 'build_year',
        'month': 'listing_month',
        'year': 'listing_year'
    },
    'flat_prices': { # 2.8k+ records
        'Title': 'property_description',
        'Price': 'price',
        'Location': 'address',
        'Surface': 'area_sqm',
        'Number_of_Rooms': 'rooms',
        'Floor': 'floor',
        'Finishing_Condition': 'condition',
        'Heating': 'heating_type',
        'Parking_Space': 'has_parking',
        'Balcony_Garden_Terrace': 'has_balcony',
        'Link': 'source_url',
        'Voivodeship': 'voivodeship',
        'City': 'city',
        'year': 'listing_year',
        'month': 'listing_month'
    },
    'olx_house_prices': { # 52k+ records
        'offer_title': 'property_description',
        'price': 'price',
        'price_per_meter': 'price_per_sqm',
        'offer_type': 'offer_type',
        'floor': 'floor',
        'area': 'area_sqm',
        'rooms': 'rooms',
        'offer_type_of_building': 'building_type',
        'market': 'market_type',
        'city_name': 'city',
        'voivodeship': 'voivodeship',
        'month': 'listing_month',
        'year': 'listing_year',
        'population': 'city_population',
        'longitude': 'longitude',
        'latitude': 'latitude'
    },
    'otodom_current_prices': { # 7k+ records
        'tytuł ogłoszenia': 'property_description',
        'link': 'source_url',
        'lokalizacja': 'address',
        'powierzchnia': 'area_sqm',
        'cena': 'price',
        'cena za metr': 'price_per_sqm',
        'czynsz': 'maintenance_fee', 
        'liczba pokoi': 'rooms',
        'rodzaj budynku': 'building_type',
        'rynek': 'market_type',
        'ogrzewanie': 'heating_type',
        'piętro': 'floor',
        'stan wykończenia': 'condition',
        'forma własności': 'ownership_type',
        'dostępne od': 'available_from', 
        'typ ogłoszeniodawcy': 'advertiser_type',
        'informacje dodatkowe': 'additional_info', 
        'rok budowy': 'build_year',
        'winda': 'has_elevator',
        'materiał budynku': 'building_material',
        'okna': 'window_type', 
        'certyfikat energetyczny': 'energy_certificate', 
        'wyposażenie': 'furnishing', 
        'zabezpieczenia': 'has_security',
        'media': 'utilities', 
        'źródło': 'source_dataset',
        'listing_year': 'listing_year', 
        'listing_month': 'listing_month',
        'city': 'city'  
    },    
    'allegro_prices': {
        # Direct column mappings - these columns already match the expected schema
        'city': 'city',
        'property_type': 'property_type',
        'area_sqm': 'area_sqm',
        'rooms': 'rooms',
        'floor': 'floor',
        'floor_count': 'floor_count',
        'build_year': 'build_year',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'distance_to_center': 'distance_to_center',
        'poi_count': 'poi_count',
        'distance_to_school': 'distance_to_school',
        'distance_to_healthcare': 'distance_to_healthcare',
        'distance_to_post_office': 'distance_to_post_office',
        'distance_to_kindergarten': 'distance_to_kindergarten',
        'distance_to_restaurant': 'distance_to_restaurant',
        'distance_to_college': 'distance_to_college',
        'distance_to_pharmacy': 'distance_to_pharmacy',
        'ownership_type': 'ownership_type',
        'has_parking': 'has_parking',
        'has_balcony': 'has_balcony',
        'has_elevator': 'has_elevator',
        'has_security': 'has_security',
        'has_storage': 'has_storage',
        'price': 'price',
        'listing_year': 'listing_year',
        'listing_month': 'listing_month',
        'price_per_sqm': 'price_per_sqm',
        'voivodeship': 'voivodeship',
        'address': 'address'
    }
}