COLUMN_MAPPINGS = {
    'apartment_prices': { # 195k+ records
        'city': 'city',
        'type': 'property_type',
        'squareMeters': 'area_sqm',
        'rooms': 'rooms',
        'floor': 'floor',
        'floorCount': 'floor_count',
        'buildYear': 'build_year',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'centreDistance': 'distance_to_center',
        'poiCount': 'poi_count',
        'schoolDistance': 'distance_to_school',
        'clinicDistance': 'distance_to_healthcare',
        'postOfficeDistance': 'distance_to_post_office',
        'kindergartenDistance': 'distance_to_kindergarten',
        'restaurantDistance': 'distance_to_restaurant',
        'collegeDistance': 'distance_to_college',
        'pharmacyDistance': 'distance_to_pharmacy',
        'ownership': 'ownership_type',
        'buildingMaterial': 'building_material',
        'condition': 'condition',
        'hasParkingSpace': 'has_parking',
        'hasBalcony': 'has_balcony',
        'hasElevator': 'has_elevator',
        'hasSecurity': 'has_security',
        'hasStorageRoom': 'has_storage',
        'price': 'price',
        'year': 'listing_year',
        'month': 'listing_month'
    },
    'house_prices': { # 20k+ records
        'address': 'address',
        'city': 'city',
        'floor': 'floor',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'price': 'price',
        'rooms': 'rooms',
        'sq': 'area_sqm',
        'build_year': 'build_year',
        'month': 'listing_month',
        'year': 'listing_year'
    },
    'flat_prices': { # 2.8k+ records
        'Title': 'property_description',
        'Price': 'price',
        'Location': 'address',
        'Surface': 'area_sqm',
        'Number_of_Rooms': 'rooms',
        'Floor': 'floor',
        'Finishing_Condition': 'condition',
        'Heating': 'heating_type',
        'Parking_Space': 'has_parking',
        'Balcony_Garden_Terrace': 'has_balcony',
        'Link': 'source_url',
        'Voivodeship': 'voivodeship',
        'City': 'city',
        'year': 'listing_year',
        'month': 'listing_month'
    },
    'olx_house_prices': { # 52k+ records
        'offer_title': 'property_description',
        'price': 'price',
        'price_per_meter': 'price_per_sqm',
        'offer_type': 'offer_type',
        'floor': 'floor',
        'area': 'area_sqm',
        'rooms': 'rooms',
        'offer_type_of_building': 'building_type',
        'market': 'market_type',
        'city_name': 'city',
        'voivodeship': 'voivodeship',
        'month': 'listing_month',
        'year': 'listing_year',
        'population': 'city_population',
        'longitude': 'longitude',
        'latitude': 'latitude'
    },
    'warsaw_flat_prices': { # 10k+ records
        'Location': 'address',
        'Price': 'price',
        'Price per m2': 'price_per_sqm',
        'Size M2': 'area_sqm',
        'Rooms': 'rooms',
        'year': 'listing_year',
        'month': 'listing_month',
        'city': 'city',
    },
    'numbers_apartment_prices': { # 62k+ records
        'ADVERTISER_TYPE': 'advertiser_type',
        'BALCONY_GARDEN_TERRACE': 'has_balcony',
        'HEATING': 'heating_type',
        'IS_FOR_SALE': 'is_for_sale',
        'LIGHTING': 'lighting',
        'LOCATION': 'address',
        'PRICE': 'price',
        'REMOTE_SUPPORT': 'has_remote_support',
        'RENT_SALE': 'offer_type',
        'SURFACE': 'area_sqm',
        'listing_year': 'listing_year',
        'listing_month': 'listing_month',
        'TITLE': 'property_description',
        'URL': 'source_url',
        'FORM_OF_PROPERTY': 'property_type',
        'NO_OF_ROOMS': 'rooms',
        'PARKING_SPACE': 'has_parking',
        'PRICE_NEW': 'price_updated',
        'SURFACE_NEW': 'area_sqm_updated',
        'SUBURB': 'district',
        'CITY': 'city',
        'COUNTRY': 'country',
        'TITLE_ENG': 'property_description_eng',
        'APARTMENT_FLAG': 'is_apartment'
    },
    'otodom_current_prices': { # 7k+ records
        'tytuł ogłoszenia': 'property_description',
        'link': 'source_url',
        'lokalizacja': 'address',
        'powierzchnia': 'area_sqm',
        'cena': 'price',
        'cena za metr': 'price_per_sqm',
        'czynsz': 'maintenance_fee', 
        'liczba pokoi': 'rooms',
        'rodzaj budynku': 'building_type',
        'rynek': 'market_type',
        'ogrzewanie': 'heating_type',
        'piętro': 'floor',
        'stan wykończenia': 'condition',
        'forma własności': 'ownership_type',
        'dostępne od': 'available_from', 
        'typ ogłoszeniodawcy': 'advertiser_type',
        'informacje dodatkowe': 'additional_info', 
        'rok budowy': 'build_year',
        'winda': 'has_elevator',
        'materiał budynku': 'building_material',
        'okna': 'window_type', 
        'certyfikat energetyczny': 'energy_certificate', 
        'wyposażenie': 'furnishing', 
        'zabezpieczenia': 'has_security',
        'media': 'utilities', 
        'źródło': 'source_dataset',
        'listing_year': 'listing_year', 
        'listing_month': 'listing_month',
        'city': 'city'  
    },
    'allegro_prices': { # 11k+ records
        'listing_url': 'source_url',
        'html_file_id': 'html_file_id',
        'title': 'property_description',
        'category': 'property_type',
        'end_date': 'end_date',
        'description': 'description',
        'Powierzchnia': 'area_sqm',
        'Cena za m²': 'price_per_sqm',
        'Rynek': 'market_type',
        'Informacje dodatkowe': 'additional_info',
        'Liczba pięter budynku': 'floor_count',
        'Ogrzewanie': 'heating_type',
        'Liczba pokoi': 'rooms',
        'Piętro': 'floor',
        'Typ budynku': 'building_type',
        'Dodatkowa powierzchnia': 'additional_area',
        'Typ kuchni': 'kitchen_type',
        'Forma własności': 'ownership_type',
        'Łazienka i WC': 'bathroom_type',
        'Rok budowy': 'build_year',
        'Materiał budowlany': 'building_material',
        'Media': 'utilities',
        'Miejsce parkingowe': 'has_parking',
        'price': 'price',
        'listing_year': 'listing_year',
        'listing_month': 'listing_month',
        'city': 'city'
    }
}